<?php

$data = array(
	array("id"=>1,"name"=>"Mia","data"=>"a, aliquet vel, vulputate eu, odio. Phasellus at augue id ante dictum cursus. Nunc mauris elit, dictum","price"=>981),
	array("id"=>2,"name"=>"Zephr","data"=>"Sed malesuada augue ut lacus. Nulla tincidunt, neque vitae semper egestas, urna justo faucibus lectus, a sollicitudin orci","price"=>340),
	array("id"=>3,"name"=>"Tanek","data"=>"eget magna. Suspendisse tristique neque venenatis lacus. Etiam bibendum fermentum metus. Aenean sed pede nec ante blandit","price"=>272),
	array("id"=>4,"name"=>"Ursa","data"=>"cubilia Curae; Phasellus ornare. Fusce mollis. Duis sit amet diam eu dolor egestas","price"=>749),
	array("id"=>5,"name"=>"Mercedes","data"=>"dolor. Fusce mi lorem, vehicula et, rutrum eu, ultrices sit amet, risus. Donec nibh enim, gravida","price"=>886),
	array("id"=>6,"name"=>"Adrian","data"=>"ipsum dolor sit amet, consectetuer adipiscing elit. Etiam laoreet, libero et tristique","price"=>478),
	array("id"=>7,"name"=>"Tanek","data"=>"Nulla aliquet. Proin velit. Sed malesuada augue ut lacus. Nulla tincidunt, neque vitae semper egestas, urna justo faucibus lectus, a","price"=>971),
	array("id"=>8,"name"=>"Blossom","data"=>"in, tempus eu, ligula. Aenean euismod mauris eu elit. Nulla","price"=>563),
	array("id"=>9,"name"=>"Stuart","data"=>"Phasellus nulla. Integer vulputate, risus a ultricies adipiscing, enim mi tempor lorem, eget mollis lectus pede et risus. Quisque","price"=>575),
	array("id"=>10,"name"=>"Cain","data"=>"arcu. Sed eu nibh vulputate mauris sagittis placerat. Cras dictum ultricies ligula. Nullam enim. Sed nulla ante, iaculis nec, eleifend","price"=>164),
	array("id"=>11,"name"=>"Faith","data"=>"Nullam velit dui, semper et, lacinia vitae, sodales at, velit. Pellentesque ultricies dignissim lacus. Aliquam","price"=>415),
	array("id"=>12,"name"=>"Sarah","data"=>"est ac facilisis facilisis, magna tellus faucibus leo, in lobortis tellus justo sit amet","price"=>989),
	array("id"=>13,"name"=>"Gabriel","data"=>"convallis erat, eget tincidunt dui augue eu tellus.","price"=>550),
	array("id"=>14,"name"=>"Imani","data"=>"enim. Sed nulla ante, iaculis nec, eleifend non, dapibus","price"=>33),
	array("id"=>15,"name"=>"Gloria","data"=>"diam lorem, auctor quis, tristique ac, eleifend vitae, erat. Vivamus","price"=>227),
	array("id"=>16,"name"=>"Wing","data"=>"tempus, lorem fringilla ornare placerat, orci lacus vestibulum lorem, sit amet ultricies sem magna nec quam. Curabitur vel lectus. Cum","price"=>423),
	array("id"=>17,"name"=>"Silas","data"=>"magnis dis parturient montes, nascetur ridiculus mus. Proin vel nisl. Quisque fringilla euismod enim. Etiam gravida molestie","price"=>819),
	array("id"=>18,"name"=>"Penelope","data"=>"facilisis facilisis, magna tellus faucibus leo, in lobortis tellus justo sit amet","price"=>835),
	array("id"=>19,"name"=>"Solomon","data"=>"blandit enim consequat purus. Maecenas libero est, congue a, aliquet vel, vulputate eu, odio. Phasellus at augue","price"=>187),
	array("id"=>20,"name"=>"Morgan","data"=>"leo elementum sem, vitae aliquam eros turpis non enim. Mauris quis turpis vitae purus gravida sagittis.","price"=>513),
	array("id"=>21,"name"=>"Eden","data"=>"Cum sociis natoque penatibus et magnis dis parturient","price"=>313),
	array("id"=>22,"name"=>"Rae","data"=>"mollis. Duis sit amet diam eu dolor egestas rhoncus. Proin nisl sem, consequat nec, mollis vitae, posuere at,","price"=>84),
	array("id"=>23,"name"=>"Merrill","data"=>"pede ac urna. Ut tincidunt vehicula risus. Nulla eget metus eu erat semper rutrum. Fusce dolor quam, elementum at, egestas","price"=>725),
	array("id"=>24,"name"=>"Travis","data"=>"nisl. Quisque fringilla euismod enim. Etiam gravida molestie arcu. Sed eu nibh","price"=>491),
	array("id"=>25,"name"=>"Robert","data"=>"a, arcu. Sed et libero. Proin mi. Aliquam gravida mauris ut mi.","price"=>362),
	array("id"=>26,"name"=>"Octavius","data"=>"a mi fringilla mi lacinia mattis. Integer eu lacus. Quisque imperdiet, erat","price"=>543),
	array("id"=>27,"name"=>"Sonya","data"=>"id sapien. Cras dolor dolor, tempus non, lacinia at, iaculis","price"=>199),
	array("id"=>28,"name"=>"Vivian","data"=>"ullamcorper, nisl arcu iaculis enim, sit amet ornare lectus justo eu","price"=>844),
	array("id"=>29,"name"=>"Hadley","data"=>"consectetuer rhoncus. Nullam velit dui, semper et, lacinia vitae, sodales at, velit. Pellentesque ultricies","price"=>846),
	array("id"=>30,"name"=>"Leonard","data"=>"Integer sem elit, pharetra ut, pharetra sed, hendrerit a, arcu. Sed","price"=>718),
	array("id"=>31,"name"=>"Teegan","data"=>"a ultricies adipiscing, enim mi tempor lorem, eget mollis lectus pede et risus. Quisque libero lacus, varius et, euismod et,","price"=>107),
	array("id"=>32,"name"=>"Marshall","data"=>"scelerisque, lorem ipsum sodales purus, in molestie tortor nibh sit amet orci. Ut sagittis lobortis mauris. Suspendisse aliquet molestie","price"=>496),
	array("id"=>33,"name"=>"Maite","data"=>"vel, mauris. Integer sem elit, pharetra ut, pharetra sed, hendrerit a, arcu. Sed et libero.","price"=>755),
	array("id"=>34,"name"=>"Maris","data"=>"Sed et libero. Proin mi. Aliquam gravida mauris ut mi. Duis risus odio, auctor vitae, aliquet nec, imperdiet nec, leo.","price"=>628),
	array("id"=>35,"name"=>"Madeson","data"=>"ornare egestas ligula. Nullam feugiat placerat velit. Quisque","price"=>245),
	array("id"=>36,"name"=>"Gray","data"=>"ac orci. Ut semper pretium neque. Morbi quis urna. Nunc quis arcu","price"=>436),
	array("id"=>37,"name"=>"MacKenzie","data"=>"Duis volutpat nunc sit amet metus. Aliquam erat volutpat.","price"=>700),
	array("id"=>38,"name"=>"Hayes","data"=>"lacinia mattis. Integer eu lacus. Quisque imperdiet, erat nonummy ultricies ornare, elit elit fermentum risus,","price"=>265),
	array("id"=>39,"name"=>"Macey","data"=>"Aliquam ornare, libero at auctor ullamcorper, nisl arcu iaculis","price"=>424),
	array("id"=>40,"name"=>"Acton","data"=>"leo, in lobortis tellus justo sit amet nulla. Donec non justo. Proin non massa non ante bibendum ullamcorper. Duis cursus,","price"=>175),
	array("id"=>41,"name"=>"Miranda","data"=>"fringilla. Donec feugiat metus sit amet ante. Vivamus non lorem vitae","price"=>398),
	array("id"=>42,"name"=>"Frances","data"=>"Phasellus vitae mauris sit amet lorem semper auctor. Mauris vel turpis. Aliquam adipiscing lobortis risus. In","price"=>755),
	array("id"=>43,"name"=>"Linda","data"=>"neque. In ornare sagittis felis. Donec tempor, est ac mattis semper, dui lectus rutrum urna, nec","price"=>330),
	array("id"=>44,"name"=>"Kadeem","data"=>"nibh sit amet orci. Ut sagittis lobortis mauris. Suspendisse aliquet molestie tellus. Aenean egestas hendrerit neque. In ornare","price"=>622),
	array("id"=>45,"name"=>"Silas","data"=>"tincidunt congue turpis. In condimentum. Donec at arcu. Vestibulum ante ipsum primis in faucibus orci luctus et","price"=>32),
	array("id"=>46,"name"=>"Adara","data"=>"sem ut cursus luctus, ipsum leo elementum sem, vitae aliquam eros turpis non enim. Mauris quis turpis vitae purus gravida","price"=>841),
	array("id"=>47,"name"=>"Bruno","data"=>"pharetra sed, hendrerit a, arcu. Sed et libero. Proin","price"=>284),
	array("id"=>48,"name"=>"Judith","data"=>"sapien. Nunc pulvinar arcu et pede. Nunc sed orci lobortis augue scelerisque mollis. Phasellus","price"=>335),
	array("id"=>49,"name"=>"Randall","data"=>"ipsum dolor sit amet, consectetuer adipiscing elit. Aliquam auctor, velit eget laoreet posuere, enim nisl elementum purus, accumsan interdum libero","price"=>174),
	array("id"=>50,"name"=>"Hammett","data"=>"tristique neque venenatis lacus. Etiam bibendum fermentum metus. Aenean sed pede nec ante blandit viverra. Donec","price"=>988),
	array("id"=>51,"name"=>"Adrian","data"=>"et magnis dis parturient montes, nascetur ridiculus mus. Proin vel nisl. Quisque fringilla euismod enim. Etiam gravida molestie arcu. Sed","price"=>239),
	array("id"=>52,"name"=>"Brennan","data"=>"Nunc mauris sapien, cursus in, hendrerit consectetuer, cursus et, magna. Praesent interdum ligula eu enim. Etiam imperdiet dictum magna. Ut","price"=>676),
	array("id"=>53,"name"=>"Tatum","data"=>"est, mollis non, cursus non, egestas a, dui. Cras pellentesque. Sed dictum. Proin","price"=>161),
	array("id"=>54,"name"=>"Judith","data"=>"risus. Nulla eget metus eu erat semper rutrum.","price"=>151),
	array("id"=>55,"name"=>"Maggie","data"=>"velit eu sem. Pellentesque ut ipsum ac mi eleifend","price"=>143),
	array("id"=>56,"name"=>"Allen","data"=>"tempus eu, ligula. Aenean euismod mauris eu elit. Nulla facilisi. Sed neque. Sed","price"=>283),
	array("id"=>57,"name"=>"Xander","data"=>"interdum enim non nisi. Aenean eget metus. In nec orci. Donec nibh. Quisque nonummy ipsum","price"=>536),
	array("id"=>58,"name"=>"Claudia","data"=>"orci. Donec nibh. Quisque nonummy ipsum non arcu. Vivamus sit amet risus. Donec egestas. Aliquam nec enim. Nunc","price"=>380),
	array("id"=>59,"name"=>"Chloe","data"=>"In ornare sagittis felis. Donec tempor, est ac mattis semper, dui lectus rutrum urna, nec luctus felis","price"=>168),
	array("id"=>60,"name"=>"Walter","data"=>"Maecenas ornare egestas ligula. Nullam feugiat placerat velit. Quisque varius.","price"=>847),
	array("id"=>61,"name"=>"Virginia","data"=>"vehicula risus. Nulla eget metus eu erat semper rutrum. Fusce dolor quam, elementum at,","price"=>421),
	array("id"=>62,"name"=>"Barry","data"=>"Mauris vel turpis. Aliquam adipiscing lobortis risus. In mi pede, nonummy ut,","price"=>625),
	array("id"=>63,"name"=>"Mikayla","data"=>"In lorem. Donec elementum, lorem ut aliquam iaculis, lacus pede sagittis augue, eu tempor erat neque non quam.","price"=>95),
	array("id"=>64,"name"=>"Clark","data"=>"lectus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec dignissim","price"=>882),
	array("id"=>65,"name"=>"Savannah","data"=>"ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec tincidunt. Donec vitae","price"=>405),
	array("id"=>66,"name"=>"Roary","data"=>"Morbi accumsan laoreet ipsum. Curabitur consequat, lectus sit amet luctus vulputate, nisi sem semper erat, in consectetuer","price"=>862),
	array("id"=>67,"name"=>"Otto","data"=>"turpis egestas. Fusce aliquet magna a neque. Nullam ut nisi a odio semper cursus. Integer mollis.","price"=>451),
	array("id"=>68,"name"=>"Amery","data"=>"risus a ultricies adipiscing, enim mi tempor lorem, eget mollis lectus","price"=>285),
	array("id"=>69,"name"=>"Samuel","data"=>"libero. Proin mi. Aliquam gravida mauris ut mi.","price"=>533),
	array("id"=>70,"name"=>"Mason","data"=>"ipsum porta elit, a feugiat tellus lorem eu metus.","price"=>706),
	array("id"=>71,"name"=>"Raphael","data"=>"justo nec ante. Maecenas mi felis, adipiscing fringilla, porttitor vulputate, posuere vulputate, lacus. Cras interdum. Nunc sollicitudin commodo","price"=>75),
	array("id"=>72,"name"=>"Oren","data"=>"vitae, orci. Phasellus dapibus quam quis diam. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis","price"=>527),
	array("id"=>73,"name"=>"Randall","data"=>"ultrices sit amet, risus. Donec nibh enim, gravida sit amet, dapibus id,","price"=>673),
	array("id"=>74,"name"=>"Willa","data"=>"Aenean egestas hendrerit neque. In ornare sagittis felis. Donec tempor, est ac mattis semper, dui lectus","price"=>427),
	array("id"=>75,"name"=>"Todd","data"=>"Etiam laoreet, libero et tristique pellentesque, tellus sem mollis dui, in sodales","price"=>826),
	array("id"=>76,"name"=>"Xavier","data"=>"lobortis ultrices. Vivamus rhoncus. Donec est. Nunc ullamcorper, velit in aliquet lobortis, nisi nibh","price"=>845),
	array("id"=>77,"name"=>"Reece","data"=>"mauris id sapien. Cras dolor dolor, tempus non, lacinia at, iaculis","price"=>339),
	array("id"=>78,"name"=>"Cedric","data"=>"ipsum dolor sit amet, consectetuer adipiscing elit. Etiam laoreet, libero et tristique pellentesque, tellus sem","price"=>628),
	array("id"=>79,"name"=>"Nina","data"=>"lorem semper auctor. Mauris vel turpis. Aliquam adipiscing lobortis risus.","price"=>45),
	array("id"=>80,"name"=>"Catherine","data"=>"Sed congue, elit sed consequat auctor, nunc nulla","price"=>477),
	array("id"=>81,"name"=>"Timothy","data"=>"ligula elit, pretium et, rutrum non, hendrerit id, ante. Nunc mauris sapien, cursus in,","price"=>581),
	array("id"=>82,"name"=>"Jemima","data"=>"urna. Nunc quis arcu vel quam dignissim pharetra. Nam ac nulla.","price"=>156),
	array("id"=>83,"name"=>"Olga","data"=>"Proin nisl sem, consequat nec, mollis vitae, posuere","price"=>353),
	array("id"=>84,"name"=>"Cleo","data"=>"auctor non, feugiat nec, diam. Duis mi enim, condimentum eget, volutpat ornare, facilisis eget, ipsum. Donec sollicitudin adipiscing","price"=>570),
	array("id"=>85,"name"=>"Gail","data"=>"ultricies ligula. Nullam enim. Sed nulla ante, iaculis nec, eleifend non, dapibus rutrum, justo. Praesent luctus. Curabitur egestas nunc","price"=>342),
	array("id"=>86,"name"=>"Chaney","data"=>"Suspendisse commodo tincidunt nibh. Phasellus nulla. Integer vulputate, risus a ultricies adipiscing, enim mi tempor lorem, eget mollis lectus pede","price"=>531),
	array("id"=>87,"name"=>"Wade","data"=>"mauris. Suspendisse aliquet molestie tellus. Aenean egestas hendrerit neque. In ornare sagittis felis. Donec tempor, est ac","price"=>906),
	array("id"=>88,"name"=>"Martin","data"=>"sem, vitae aliquam eros turpis non enim. Mauris quis turpis vitae purus gravida","price"=>861),
	array("id"=>89,"name"=>"Hilary","data"=>"semper erat, in consectetuer ipsum nunc id enim. Curabitur massa. Vestibulum accumsan neque et nunc. Quisque","price"=>154),
	array("id"=>90,"name"=>"Jaime","data"=>"egestas blandit. Nam nulla magna, malesuada vel, convallis in, cursus et, eros. Proin ultrices. Duis volutpat nunc sit","price"=>547),
	array("id"=>91,"name"=>"Aphrodite","data"=>"cursus non, egestas a, dui. Cras pellentesque. Sed dictum. Proin eget odio. Aliquam vulputate ullamcorper","price"=>252),
	array("id"=>92,"name"=>"Brett","data"=>"Aliquam nec enim. Nunc ut erat. Sed nunc est, mollis non, cursus","price"=>557),
	array("id"=>93,"name"=>"Beau","data"=>"elit fermentum risus, at fringilla purus mauris a nunc. In at pede. Cras vulputate velit","price"=>695),
	array("id"=>94,"name"=>"Uriah","data"=>"consequat dolor vitae dolor. Donec fringilla. Donec feugiat metus sit amet ante. Vivamus non","price"=>344),
	array("id"=>95,"name"=>"Autumn","data"=>"ligula eu enim. Etiam imperdiet dictum magna. Ut tincidunt orci quis lectus. Nullam","price"=>283),
	array("id"=>96,"name"=>"Megan","data"=>"nisi. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin vel nisl. Quisque","price"=>943),
	array("id"=>97,"name"=>"Cheryl","data"=>"ut ipsum ac mi eleifend egestas. Sed pharetra, felis eget varius ultrices, mauris ipsum porta elit, a","price"=>733),
	array("id"=>98,"name"=>"Shelley","data"=>"mollis nec, cursus a, enim. Suspendisse aliquet, sem ut cursus luctus, ipsum leo elementum","price"=>661),
	array("id"=>99,"name"=>"Hilary","data"=>"et malesuada fames ac turpis egestas. Fusce aliquet magna a neque. Nullam ut nisi a odio semper cursus. Integer mollis.","price"=>850),
	array("id"=>100,"name"=>"Nina Fofilina","data"=>"mauris, rhoncus id, mollis nec, cursus a, enim. Suspendisse aliquet, sem ut cursus luctus, ipsum","price"=>963)
);

// Pentru fiecare produs, adaugam o rubrica 'url'
// 'url' => 'chloe-59';
// Acesta este obtinut din combinatia numelui si id
foreach ($data as $index => $value) {
	// Numele este trasformat in litere mici
	// Iar spatiile din nume in '-';
	$data[$index]['url'] = strtolower(str_replace(' ', '-', $data[$index]['name'])) . '-' . $data[$index]['id'];
}